---
apiVersion: v1
kind: Service
metadata:
  name: ers
  labels:
    app: ers
spec:
  type: NodePort
  selector:
    app: ers
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ers
spec:
  selector:
    matchLabels:
      app: ers
  replicas: 1
  template:
    metadata:
      labels:
        app: ers
    spec:
      containers:
      - name: ers
        image: bayalew/ers:latest
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1