---
kind: Service
apiVersion: v1
metadata:
  name: horizon2
  labels:
    app: horizon2
spec:
  type: NodePort
  selector:
    app: horizon2
  ports:
  - port: 8020
    targetPort: 8090
    protocol: TCP
    nodePort: 31000
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon2
spec:
  selector:
    matchLabels:
      app: horizon2
  replicas: 2
  template:
    metadata:
      labels:
        app: horizon2
    spec:
      containers:
      - name: horizon2
        image: host.docker.internal:5000/horizon-local
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: actuator/health
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1