server:
    port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver 
    url: "jdbc:postgresql://localhost:5432/horizontest"
    username: postgres
    password: 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

#server:
#    port: 8080      
#spring:
#  datasource: 
#    url: jdbc:h2:mem:mydb
#    username: user
#    password: pass
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: create
#  h2:
#    console:
#      enabled: true